feat: unified homescreen with search and sort
zeno-ml/zeno-hub pull request #379
Opened 2023-10-31 01:29 UTC by cabreraalex

# Description

2023-10-31 19:09 UTC, Sparkier requested changes
Overall really like these changes. Only minor things.

I know you wanted this for differentiation, but it looks like reports is selected:
<img width="245" alt="image" src="https://github.com/zeno-ml/zeno-hub/assets/5690524/989648a0-72d7-43ac-b2db-6833208230af">

Also here, I agree we need differentiation but I don't think this is it. Looks like it's selected to me:
<img width="648" alt="image" src="https://github.com/zeno-ml/zeno-hub/assets/5690524/98666d81-fd65-4428-8611-4777ae142e9a">

The size difference here looks off IMHO:
<img width="642" alt="image" src="https://github.com/zeno-ml/zeno-hub/assets/5690524/b7500afd-c61d-418f-87ae-80f4b607921f">

Maybe just me but I liked the top banner better when it was lighter.

Is there something wrong for me here?
<img width="128" alt="image" src="https://github.com/zeno-ml/zeno-hub/assets/5690524/092572e9-be4a-42e3-9005-28274090e267">

Personally don't like this as much but might just be taste. Generally mixing these changes in these big PRs makes it so that both take longer to get in so maybe better to separate out in the future:
<img width="2910" alt="image" src="https://github.com/zeno-ml/zeno-hub/assets/5690524/1b013a89-c1d1-4fc5-91d1-6243d9f9958b">

Maybe we can move the search and filter stuff all to the top right generally? Might look better.

Do we want to remove this or did you just forget about it:
<img width="638" alt="image" src="https://github.com/zeno-ml/zeno-hub/assets/5690524/c3db5614-fdc5-44c9-bee6-8c04b5048aaa">

2023-10-31 21:27 UTC, cabreraalex commented on backend/zeno_backend/classes/homepage.py
> +    REPORT = "REPORT"
Maybe `EntryTypeFilter`? `TypeFilter` probably too generic.

2023-10-31 22:34 UTC, cabreraalex commented on backend/zeno_backend/database/insert.py
> +            return False
It does one step up

2023-10-31 22:41 UTC, cabreraalex commented on backend/zeno_backend/server.py
> +        return select.projects(user, HomeRequest())
Yeah reports needs it

2023-10-31 22:42 UTC, cabreraalex commented on backend/zeno_backend/server.py
> +        return select.reports(user, HomeRequest())
Nope!

2023-10-31 22:42 UTC, cabreraalex commented on frontend/src/lib/components/report/Report.svelte
> +			{#if report.description.length > 100}
Combined!

2023-10-31 22:43 UTC, cabreraalex commented on backend/zeno_backend/classes/homepage.py
> +    search_string: str = ""
I think for now it'll all be on home. can refactor/rename later if this changes?

2023-10-31 22:44 UTC, cabreraalex commented on backend/zeno_backend/classes/homepage.py
> +    REPORT = "REPORT"
Gonna leave as Home for now until we have a use for it elsewhere.

2023-10-31 22:48 UTC, cabreraalex commented on backend/zeno_backend/database/select.py
> +
Eventually when we use limit and offset we don't want to get all entries in python - we'll get the top N * 2 for both projects and reports and then sort again the limited options in python was my thinking.

2023-10-31 23:36 UTC, cabreraalex commented
It's ugly but I couldn't come up with anything better currently.

<img width="1421" alt="Screenshot 2023-10-31 at 16 35 41" src="https://github.com/zeno-ml/zeno-hub/assets/4563691/1dfc5089-ab75-4142-adf6-5fb079b74005">

IMO feel free to update design stuff however you want, if you don't find any big issues I'm down to merge and deploy to fix some of the homepage issues. We can then do a bigger refactor/clean up of the homepage.

2023-11-01 08:43 UTC, Sparkier commented
Think it looks much better than before. Still feel like reports have more prominence with this highlighting which we should probably avoid but should get this in for now.

2023-11-01 08:43 UTC, merged