feat: add buttons to copy all ids of a slice's/tag's instances
zeno-ml/zeno-hub pull request #479
Opened 2023-11-24 15:16 UTC by Sparkier

# Description

fix ZEN-370

2023-11-24 21:07 UTC, cabreraalex requested changes

2023-11-24 21:07 UTC, cabreraalex commented on backend/zeno_backend/database/select.py
> +        final_statement = sql.SQL(" ").join(
Can this just be:

`sql.SQL("SELECT {} FROM {}").format(sql.Identifier(id_column.id), sql.Identifier(uuid)))`

2023-11-24 21:07 UTC, cabreraalex commented on backend/zeno_backend/database/select.py
> +        if db.cur is None:
I don't think you need a cursor for this function.

2023-11-24 21:07 UTC, cabreraalex commented on backend/zeno_backend/routers/slice.py
> +    "/slice_instance_ids/{slice_id}/{model}", response_model=list[str], tags=["zeno"]
should be dashes?

2023-11-24 21:07 UTC, cabreraalex commented on frontend/src/lib/components/metadata/cells/SliceCell.svelte
> +								<Icon style="font-size: 18px;" class="material-icons">delete_outline</Icon>&nbsp;
change icon for this and other one

2023-11-24 21:07 UTC, cabreraalex commented on frontend/src/lib/components/metadata/cells/TagCell.svelte
> +									navigator.clipboard.writeText(tag.dataIds.toString());
I think this should copy with the two brackets `[ ]` around it so you can just directly paste into Python.

2023-11-25 09:01 UTC, Sparkier commented
Thanks. Fixed.

2023-11-25 15:15 UTC, cabreraalex approved these changes

2023-11-25 15:15 UTC, merged