fix: move help to top bar, move project settings to top bar
zeno-ml/zeno-hub pull request #568
Opened 2023-12-14 01:22 UTC by cabreraalex

# Description
Why?
1. Makes settings in a consistent place across all views
2. Makes help a bit more discoverable, same in all views, not hacky depending on what is shown where.

2023-12-14 08:33 UTC, Sparkier requested changes
I like the settings moving up. Am ok with help also moving but think it's much less prominent now. Might be fine since we're starting to link to docs from other places (e.g. reports).

If we keep it like this, I think we definitely should add it to the playground as well.

2023-12-14 08:33 UTC, Sparkier commented on frontend/src/lib/components/general/Header.svelte
> +<div class="mx-6 mb-4 mt-4 flex h-8 items-center justify-between">
nit: my-4

2023-12-14 08:33 UTC, Sparkier commented on frontend/src/lib/components/general/UserButton.svelte
>  	{/if}
Should we move this in here? Will make it difficult if we ever want to add it to somewhere else (e.g. playground)

2023-12-15 16:39 UTC, cabreraalex commented
Made it a component and added to playground!

2023-12-15 16:44 UTC, Sparkier approved these changes

2023-12-15 16:44 UTC, Sparkier commented on frontend/src/lib/components/general/HelpButton.svelte
> +	let docsLink = 'https://zenoml.com/docs/intro';
Used this as export to deep-link to different parts of the docs previously but probably not necessary anymore.

2023-12-15 16:46 UTC, merged